default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_app_development

test:
  <<: *default
  database: Recipe_app_test

production:
  <<: *default
  database: Recipe_app_production
 